# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'HouseworkSharingApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HouseworkSharingApp
  pod 'SwiftLint'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'HouseworkSharingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

    # Pods for testing
  end
